# Generated by Django 3.1.4 on 2020-12-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echo',
            old_name='title',
            new_name='message',
        ),
    ]
