# Generated by Django 3.1.5 on 2021-01-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='courseNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='courseNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='labexperience',
            name='courseNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='courseNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='courseNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
    ]
