# Generated by Django 3.1.5 on 2021-01-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduateattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='graduateattribute',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='oid',
        ),
    ]
