# Generated by Django 3.1.5 on 2021-01-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210112_0446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outcome',
            unique_together={('oid', 'courseNumber')},
        ),
    ]
