# Generated by Django 3.1.5 on 2021-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210116_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academicCredit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='labHours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lectureHours',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
