# Generated by Django 3.1.5 on 2021-01-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210113_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateattribute',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.outcome'),
        ),
    ]
