# Generated by Django 3.1.5 on 2021-01-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210116_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateattribute',
            name='gid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
