# Generated by Django 3.1.5 on 2021-01-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210113_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='cs1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='cs2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='csAU',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='edAU',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='esAU',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='math1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='math2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='mathAU',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='ns1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='ns2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='nsAU',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
