# Generated by Django 3.1.5 on 2021-01-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210113_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='labNSPS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='labSections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lablHours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lectureHours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lectureNSPS',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lectureSections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='tutorialHours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='tutorialNSPS',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='tutorialSections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
