# Generated by Django 3.1.5 on 2021-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210113_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='projectWeight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
