# Generated by Django 3.1.5 on 2021-01-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_finalgrade_projectweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='lablHours',
            new_name='labHours',
        ),
    ]
